const path = require('path');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const { IgnorePlugin } = require('webpack');

/**
 * Custom webpack configuration for NestJS core-api service.
 * 
 * This config extends the default NestJS webpack config to:
 * 1. Copy Prisma schema to dist folder
 * 2. Copy Linux Prisma binary (debian-openssl-3.0.x) for Azure App Service deployment
 * 3. Ignore optional dependencies of node-pre-gyp (used by bcrypt)
 * 
 * The binary targets are configured in prisma/schema.prisma:
 *   binaryTargets = ["native", "debian-openssl-3.0.x"]
 */
module.exports = function (options) {
  return {
    ...options,
    externalsType: 'commonjs', // Ensure externals use CommonJS require()
    module: {
      ...options.module,
      rules: [
        ...(options.module?.rules || []),
        {
          test: /\.html$/,
          type: 'asset/source',
        },
      ],
    },
    plugins: [
      ...options.plugins,
      // Ignore optional dependencies that cause webpack build errors
      new IgnorePlugin({
        checkResource(resource) {
          const lazyImports = [
            '@nestjs/microservices',
            '@nestjs/websockets/socket-module',
            'cache-manager',
            'class-validator',
            'class-transformer',
            // node-pre-gyp optional deps (fixes bcrypt build)
            'aws-sdk',
            'nock',
            'mock-aws-s3',
          ];
          if (!lazyImports.includes(resource)) {
            return false;
          }
          try {
            require.resolve(resource, {
              paths: [process.cwd()],
            });
          } catch (err) {
            return true;
          }
          return false;
        },
      }),
      new CopyWebpackPlugin({
        patterns: [
          // Create minimal package.json (required by some runtime code, e.g., Prisma, bcrypt)
          // We create a minimal version to avoid pnpm treating dist/ as a workspace
          // But include fields needed by node-pre-gyp (used by bcrypt)
          {
            from: path.resolve(__dirname, 'package.json'),
            to: path.resolve(__dirname, 'dist/package.json'),
            transform(content) {
              const pkg = JSON.parse(content.toString());
              // Include fields needed at runtime, especially for node-pre-gyp validation
              // node-pre-gyp (used by bcrypt) validates package.json and needs these fields
              return JSON.stringify({
                name: pkg.name,
                version: pkg.version,
                private: true,
                main: 'main.js',
                binary: {
                  module_name: 'bcrypt_lib',
                  module_path: './lib/binding',
                  host: 'https://github.com'
                }
              }, null, 2);
            },
          },
          // Copy Prisma schema (required for Prisma client to work)
          {
            from: path.resolve(__dirname, 'prisma/schema.prisma'),
            to: path.resolve(__dirname, 'dist/prisma/schema.prisma'),
          },
          // Copy Linux Prisma query engine binary for Azure App Service
          // The binary is generated by `prisma generate` with binaryTargets in schema.prisma
          {
            from: path.resolve(
              __dirname,
              '../../node_modules/.prisma/client/libquery_engine-debian-openssl-3.0.x.so.node'
            ),
            to: path.resolve(__dirname, 'dist/'),
            noErrorOnMissing: true, // Don't fail if binary doesn't exist (e.g., on Windows)
          },
          // Copy bcrypt native module (marked as external, so we need to copy it)
          {
            from: path.resolve(__dirname, '../../node_modules/bcrypt'),
            to: path.resolve(__dirname, 'dist/node_modules/bcrypt'),
            globOptions: {
              ignore: ['**/test/**', '**/*.md', '**/CHANGELOG.md'],
            },
            noErrorOnMissing: true,
          },
        ],
      }),
    ],
      // Mark bcrypt as external - it's a native module that can't be bundled
      // We'll copy it separately to dist
      externals: [
        ...(options.externals || []),
        'bcrypt',
      ],
  };
};

