const path = require('path');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const { IgnorePlugin } = require('webpack');

/**
 * Custom webpack configuration for NestJS core-api service.
 * 
 * This config extends the default NestJS webpack config to:
 * 1. Copy Prisma schema to dist folder
 * 2. Copy Linux Prisma binary (debian-openssl-3.0.x) for Azure App Service deployment
 * 3. Ignore optional dependencies of node-pre-gyp (used by bcrypt)
 * 
 * The binary targets are configured in prisma/schema.prisma:
 *   binaryTargets = ["native", "debian-openssl-3.0.x"]
 */
module.exports = function (options) {
  return {
    ...options,
    module: {
      ...options.module,
      rules: [
        ...(options.module?.rules || []),
        {
          test: /\.html$/,
          type: 'asset/source',
        },
      ],
    },
    plugins: [
      ...options.plugins,
      // Ignore optional dependencies that cause webpack build errors
      new IgnorePlugin({
        checkResource(resource) {
          const lazyImports = [
            '@nestjs/microservices',
            '@nestjs/websockets/socket-module',
            'cache-manager',
            'class-validator',
            'class-transformer',
            // node-pre-gyp optional deps (fixes bcrypt build)
            'aws-sdk',
            'nock',
            'mock-aws-s3',
          ];
          if (!lazyImports.includes(resource)) {
            return false;
          }
          try {
            require.resolve(resource, {
              paths: [process.cwd()],
            });
          } catch (err) {
            return true;
          }
          return false;
        },
      }),
      new CopyWebpackPlugin({
        patterns: [
          // Create minimal package.json (required by some runtime code, e.g., Prisma)
          // We create a minimal version to avoid pnpm treating dist/ as a workspace
          {
            from: path.resolve(__dirname, 'package.json'),
            to: path.resolve(__dirname, 'dist/package.json'),
            transform(content) {
              const pkg = JSON.parse(content.toString());
              // Only include fields needed at runtime
              return JSON.stringify({
                name: pkg.name,
                version: pkg.version,
                private: true
              }, null, 2);
            },
          },
          // Copy Prisma schema (required for Prisma client to work)
          {
            from: path.resolve(__dirname, 'prisma/schema.prisma'),
            to: path.resolve(__dirname, 'dist/prisma/schema.prisma'),
          },
          // Copy Linux Prisma query engine binary for Azure App Service
          // The binary is generated by `prisma generate` with binaryTargets in schema.prisma
          {
            from: path.resolve(
              __dirname,
              '../../node_modules/.prisma/client/libquery_engine-debian-openssl-3.0.x.so.node'
            ),
            to: path.resolve(__dirname, 'dist/'),
            noErrorOnMissing: true, // Don't fail if binary doesn't exist (e.g., on Windows)
          },
        ],
      }),
    ],
    // Fix for "Can't resolve 'cardinal', 'pg-hstore', etc." in some libs
    externals: [
      ...(options.externals || []),
      // Mark bcrypt as external if bundling fails, but trying IgnorePlugin first
    ],
  };
};

