const path = require('path');
const CopyWebpackPlugin = require('copy-webpack-plugin');

/**
 * Custom webpack configuration for NestJS core-api service.
 * 
 * This config extends the default NestJS webpack config to:
 * 1. Copy Prisma schema to dist folder
 * 2. Copy Linux Prisma binary (debian-openssl-3.0.x) for Azure App Service deployment
 * 
 * The binary targets are configured in prisma/schema.prisma:
 *   binaryTargets = ["native", "debian-openssl-3.0.x"]
 */
module.exports = function (options) {
  return {
    ...options,
    plugins: [
      ...options.plugins,
      new CopyWebpackPlugin({
        patterns: [
          // Copy Prisma schema (required for Prisma client to work)
          {
            from: path.resolve(__dirname, 'prisma/schema.prisma'),
            to: path.resolve(__dirname, 'dist/prisma/schema.prisma'),
          },
          // Copy Linux Prisma query engine binary for Azure App Service
          // The binary is generated by `prisma generate` with binaryTargets in schema.prisma
          {
            from: path.resolve(
              __dirname,
              '../../node_modules/.prisma/client/libquery_engine-debian-openssl-3.0.x.so.node'
            ),
            to: path.resolve(__dirname, 'dist/'),
            noErrorOnMissing: true, // Don't fail if binary doesn't exist (e.g., on Windows)
          },
        ],
      }),
    ],
  };
};

